[application]

# App (Project) Name
name = "dioxus-wallet-adapter"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "dioxus-wallet-adapter"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = [
    "./main.css",
    "https://fonts.googleapis.com/css2?family=Anton+SC&display=swap",
    "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
]

# Javascript code file
script = ["./main.js"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
